# Copyright 2025 Xiaomi Corporation.

dataset_path: ${MIMO_DATA_ROOT}/vqa/Part-Affordance-2K
task: part_affordance
test_split: train
dataset_kwargs:
  token: False

output_type: generate_until
doc_to_visual: !function utils.partaffordance_doc_to_visual
doc_to_text: !function utils.partaffordance_doc_to_text_mimo
doc_to_target: "mask"
generation_kwargs:
  max_new_tokens: 32768
  do_sample: false
  temperature: 0.0
filter_list:
  - name: point-extract
    filter:
      - function: !function utils.PointFilter
# The return value of process_results will be used by metrics
process_results: !function utils.partaffordance_process_results
metric_list:
  - metric: accuracy   
    aggregation: !function utils.partaffordance_aggregate_results
    higher_is_better: true
metadata:
  - version: 0.0
