# Copyright 2025 Xiaomi Corporation.

dataset_path: json
task: metavqa_eval
test_split: test
dataset_kwargs:
  data_files:
    test: ${MIMO_DATA_ROOT}/vqa/MetaVQA-Eval/test.jsonl

img_root: "${MIMO_DATA_ROOT}/vqa/MetaVQA-Eval"
output_type: generate_until
doc_to_visual: !function utils.metavqa_doc_to_visual
doc_to_text: !function utils.metavqa_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 32768
  temperature: 0.0 
  top_p: 1.0 
  num_beams: 1
  do_sample: false
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nPut your final answer in \\boxed{}."
filter_list:
  - name: "flexible-extract"
    filter:
      - function: !function utils.BoxedFilter
# The return value of process_results will be used by metrics
process_results: !function utils.metavqa_process_results
metric_list:
  - metric: accuracy   
    aggregation: !function utils.metavqa_aggregate_results
    higher_is_better: true
metadata:
  - version: 0.0

